blog/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<id>\d+)/$', views.post_detail, name='post_detail'),

    url(r'^new/$', views.post_new, name='post_new'),

    url(r'(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),

    url(r'^cbv/new/$', views_cbv.post_new),
]

practice2/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.shortcuts import redirect

from django.conf.urls.static import static
#def root(request):
#    return redirect('blog:post_list')

urlpatterns = [
    #url(r'^$', root, name='root'),
    url(r'^$', lambda r: redirect('blog:post_list'), name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

blog/models.py
from django.db import models
from django.conf import settings
from django.forms import ValidationError
from django.core.urlresolvers import reverse
import re


def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')

# Create your models here.
class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    #author = models.CharField(max_length=20)
    title = models.CharField(max_length=100, verbose_name='제목', help_text='포스팅 제목을 입력해주세요. 최대 100자 내외')
    content = models.TextField(verbose_name='내용')

    photo = models.ImageField(blank=True)

    tags = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=50, blank=True, help_text='경도/위도 포맷으로 입력', validators=[lnglat_validator])
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)

    tag_set = models.ManyToManyField('Tag', blank=True)
    #문자열로 지정해도 인식됨. Tag가 아래 있으므로 Tag로 못 씀. 'Tag'로 써야함.
    created_at = models.DateTimeField(auto_now_add=True) #auto_now_add 최초에만
    updated_at = models.DateTimeField(auto_now=True) #auto_now 업데이트할때마다

    class Meta:
        ordering = ['-id'] #필드수는 1~2개만 쓰는게 성능 높이는데 좋음

    def __str__(self): #포스트에 글들이 다 Post object로 나오는데 title로 바꾸기 위함
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id]) ## /blog/detail/4


class Ask(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self): #str은 모델에다 쓰는 거였군.
        return self.name

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'





#폼자체는 폼을 만들기 위한 것이여. 그리고 이진석 강사님은 이 폼을 쓰면 좋다고 하시는 거고

blog/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from .models import Post, Ask
from django.http import Http404
from .forms import PostForm
#from .models import Ask


def post_list(request):
    qs = Post.objects.all()

    q = request.GET.get('q', '')
    f = request.GET.get('f', '')

    Ask.objects.create(title=f)

    if q:
        qs = qs.filter(title__icontains=q)

    #messages.error(request, '에러메세지 테스트')

    return render(request, 'blog/post_list.html', { 'post_list': qs,
            'q' : q
        })
# Create your views here.


def post_detail(request,id):
    #try:
    #    post = Post.objects.get(id=id)
    #except Post.DoesNotExist:
    #    raise Http404
    post = get_object_or_404(Post, id=id)

    return render(request, 'blog/post_detail.html', {
        'post': post,
    })



def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.success(request, '새 포스팅을 저장했습니다.')
            return redirect(post)
    else:
        form = PostForm()

    return render(request, 'blog/post_form.html', {
        'form': form,
    })

def post_edit(request, id):

    post = get_object_or_404(Post, id=id)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance= post)
        if form.is_valid():
            post = form.save()
            messages.success(request, '수정이 완료되었습니다.')
            return redirect(post)
    else:
        form = PostForm(instance= post)

    return render(request, 'blog/post_form.html', {
        'form': form,
    })

blog/templates/blog/layout.html
{% extends "layout.html" %}

{% block title %}AskDjango's Blog{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block title %}
{{ post.title }}
{% endblock %}


{% block content %}

    <h2>{{ post.title }}</h2>

    {{ post.content|linebreaks }}

    <hr/>

    <h3>Comments</h3>

    <ul>
    {% for comment in post.comment_set.all %}
        <li>
        {{ comment.message}}
        <small>by {{ comment.author }}</small>
        <small>at {{ comment.updated_at }}</small>
        </li>
    {% endfor %}
    </ul>

    <hr/>

    <a href="{% url "blog:post_list" %}">글 목록</a>
    <a href="{% url "blog:post_edit" post.id %}">수정</a>

{% endblock %}

blog/templates/blog/post_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}

<p>아니 그게 아니라...</p>

<a href="{% url "blog:post_new" %}">New Post</a>
<form>
    <input type="text" name='q' value="{{ q }}" />
    <input type="submit" value="검색" />
</form>


<ul>
{% for post in post_list %}
    <li>
        {{ post.id }}
        <a href="{% url "blog:post_detail" post.id %}">
        {{ post.title }}
        </a>
    </li>
{% endfor %}
</ul>

<p>찾으시는 문서가 없으신가요?</p>
<p>원하시는 문서를 신청해보세요! 신청 후 문서가 업로드되면 1000P를 드립니다! </p>

<form>
    <input type="text" name="f"/>
    <input type="submit" value="신청하기"/>
</form>


{% endblock %}